[package]
name = "shelf"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Eric Zhao <21zhaoe@protonmail.com>"]
description = "Dotfiles package manager."
homepage = "https://github.com/Dophin2009/shelf"
repository = "https://github.com/Dophin2009/shelf.git"
edition = "2018"

[dependencies]
clap = { version = "3.1.17", features = ["derive"] }
crossterm = "0.23.2"
directories-next = "2.0.0"
log = "0.4.17"
once_cell = "1.10.0"
paste = "1.0.7"
pathdiff = "0.2.1"
stderrlog = "0.5.1"

shelflib = { path = ".." }

[features]
default = []
vendor = ["shelflib/lua-vendor"]
unsafe = ["shelflib/lua-unsafe"]
