[package]
name = "shelf"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Eric Zhao <21zhaoe@protonmail.com>"]
description = "Dotfiles package manager."
homepage = "https://github.com/Dophin2009/shelf"
repository = "https://github.com/Dophin2009/shelf.git"
edition = "2018"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
crossterm = "0.22"
directories-next = "2.0"
log = "0.4"
paste = "1.0"
pathdiff = "0.2"
stderrlog = "0.5"

shelflib = { path = "..", features = ["lua54"] }

[features]
default = []
vendor = ["shelflib/lua-vendor"]
unsafe = ["shelflib/lua-unsafe"]
