[package]
name = "stew"
version = "0.1.0"
authors = ["Eric Zhao <21zhaoe@protonmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.1"
glob = "0.3.0"
gtmpl = "0.5.7"
gtmpl_derive = "0.3.3"
gtmpl_value = "0.3.3"
handlebars = "3.4.0"
log = "0.4.0"
petgraph = "0.5.1"
serde = "1.0.115"
serde_dhall = "0.6.0"
shlex = "0.1.1"
stderrlog = "0.4.3"
