[package]
name = "tidy"
version = "0.3.0"
authors = ["Eric Zhao <21zhaoe@protonmail.com>"]
description = "Keep your dotfiles tidy."
homepage = "https://github.com/Dophin2009/tidy"
repository = "https://github.com/Dophin2009/tidy.git"
license = "GPL-3.0-or-later"
edition = "2018"
build = "build.rs"

[lib]
name = "tidy"
path = "src/lib.rs"

[[bin]]
name = "tidy"
path = "src/main.rs"

[features]
default = []
lua51 = ["mlua.lua51"]
lua52 = ["mlua.lua52"]
lua53 = ["mlua.lua53"]
lua54 = ["mlua.lua54"]
luajit = ["mlua.luajit"]
unsafe = []

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
log = "0.4"
mlua = { version = "0.6", features = ["send", "serialize"] }
petgraph = "0.5"
serde = { version = "1.0", features = ["derive"] }
stderrlog = "0.5"
