[package]
authors = ["Eric Zhao <21zhaoe@protonmail.com>"]
build = "build.rs"
description = "Keep your dotfiles tidy."
edition = "2018"
homepage = "https://github.com/Dophin2009/tidy"
license = "GPL-3.0-or-later"
name = "tidy"
repository = "https://github.com/Dophin2009/tidy.git"
version = "0.3.0"

[[bin]]
name = "tidy"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
bunt = "0.2"
bunt-logger = "0.1"
clap = "3.0.0-beta.4"
directories-next = "2.0"
glob = "0.3"
handlebars = "4.1"
home = "0.5"
liquid = "0.22"
once_cell = "1.8"
path-clean = "0.1"
petgraph = "0.6"
serde_json = "1.0"
serde_yaml = "0.8"
thiserror = "1.0"
toml = "0.5"

[dependencies.mlua]
features = ["macros", "send", "serialize"]
version = "0.6"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.uuid]
features = ["v4"]
version = "0.8"

[features]
default = []
lua51 = ["mlua/lua51"]
lua52 = ["mlua/lua52"]
lua53 = ["mlua/lua53"]
lua54 = ["mlua/lua54"]
luajit = ["mlua/luajit"]
unsafe = []
